name: multiutillib
description: A new Flutter package with multiple utilities to use on the go and ease in development process.
version: 1.3.2
homepage: https://github.com/amitjangid80/multiutillib_flutter.git

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  # simple_animations: ^5.0.0+2
  sa4_migration_kit: ^1.0.0
  connectivity_plus: ^4.0.2
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
  assets:
    - assets/gif/double_ring_loading_io.gif
