name: multiutillib
description: A new Flutter package with multiple utilities to use on the go and ease in development process.
version: 1.4.0
maintainer: Amit Jangid (jangidamit800@gmail.com)
homepage: https://github.com/amitjangid80/multiutillib_flutter.git
issue_tracker: https://github.com/amitjangid80/multiutillib_flutter/issues
topics:
- utilities
- extensions

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  # simple_animations: ^5.0.0+2
  sa4_migration_kit: ^1.0.0
  connectivity_plus: ^6.0.5
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
  - assets/gif/double_ring_loading_io.gif
