name: multiutillib
description: A new Flutter package with multiple utilities to use on the go and ease in development process.
version: 1.2.0
# authors:
  # - Amit Jangid<amitjangid80@yahoo.in>
homepage: https://github.com/amitjangid80/multiutillib_flutter.git

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  intl: ^0.17.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.2
  device_info_plus: ^3.2.3
  package_info_plus: ^1.4.2
  simple_animations: ^4.0.2
  connectivity_plus: ^2.3.2
  loading_animation_widget: ^1.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
  assets:
    - assets/gif/double_ring_loading_io.gif
