name: "multiutillib"

on:
  push:
    branches:
      - master

jobs:
    build:
      runs-on: macos-latest
      timeout-minutes: 30
      steps:
        - name: "Checkout Repository"
          uses: actions/checkout@v2
        - name: "Install Flutter"
          uses: ./.github/worksflows/scripts/install-flutter.sh stable
        - name: "Install Tools"
          uses: ./.github/worksflows/scripts/install-tools.sh
        - name: "Getting Packages"
          run: flutter pub get
